DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbWFycGFua29pcmFsYUBnbWFpbC5jb20iLCJleHAiOjE3NjE3MDE4NDksInVzZXJJZCI6MH0.BUsWTJpA0MSC5U7EeP9dRZxjdjy6BWD1Hi1YKG2kyxA
